# Generated by Django 2.1.14 on 2019-11-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0016_auto_20190525_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='ocr',
            field=models.BinaryField(null=True),
        ),
    ]
