FROM buildpack-deps:bullseye

# Setup the python environment
# All of this tomfoolery can be replaced with just using a python Docker image for Debian bullseye
# ...when such an image becomes available, of course

# ensure local python is preferred over distribution python
ENV PATH /usr/local/bin:$PATH

# http://bugs.python.org/issue19846
# > At the moment, setting "LANG=C" on a Linux system *fundamentally breaks Python 3*, and that's not OK.
ENV LANG C.UTF-8

# extra dependencies (over what buildpack-deps already includes)
RUN apt-get update && apt-get install -y --no-install-recommends \
		tk-dev \
		uuid-dev \
	&& rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y python3 python3-dev

# make some useful symlinks that are expected to exist
RUN cd /usr/local/bin \
	&& ln -fs idle3 idle \
	&& ln -fs pydoc3 pydoc \
	&& ln -fs python3 python \
	&& ln -fs python3-config python-config

# if this is called "PIP_VERSION", pip explodes with "ValueError: invalid truth value '<VERSION>'"
ENV PYTHON_PIP_VERSION 19.3.1
# https://github.com/pypa/get-pip
ENV PYTHON_GET_PIP_URL https://github.com/pypa/get-pip/raw/ffe826207a010164265d9cc807978e3604d18ca0/get-pip.py
ENV PYTHON_GET_PIP_SHA256 b86f36cc4345ae87bfd4f10ef6b2dbfa7a872fbff70608a1e43944d283fd0eee

RUN set -ex; \
	\
	wget -O get-pip.py "$PYTHON_GET_PIP_URL"; \
	echo "$PYTHON_GET_PIP_SHA256 *get-pip.py" | sha256sum --check --strict -; \
	\
	python3 get-pip.py \
		--disable-pip-version-check \
		--no-cache-dir \
		"pip==$PYTHON_PIP_VERSION" \
	; \
	pip --version; \
	\
	find /usr/local -depth \
		\( \
			\( -type d -a \( -name test -o -name tests -o -name idle_test \) \) \
			-o \
			\( -type f -a \( -name '*.pyc' -o -name '*.pyo' \) \) \
		\) -exec rm -rf '{}' +; \
	rm -f get-pip.py

# Setup our app

WORKDIR /app

RUN apt-get update && apt-get -y install poppler-utils tesseract-ocr libtesseract-dev libleptonica-dev pkg-config

RUN pip install uwsgi

ADD requirements.txt .

RUN pip install -r requirements.txt

ADD app .

CMD "./entrypoint.sh"
