# Generated by Django 2.1.7 on 2019-03-16 13:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_annotation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='publication_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publication',
            name='file_url',
            field=models.URLField(unique=True),
        ),
    ]
