# Generated by Django 2.1.7 on 2019-04-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_auto_20190316_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='file_url',
            new_name='remote_file',
        ),
        migrations.AddField(
            model_name='publication',
            name='local_file',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
