# Generated by Django 2.1.7 on 2019-04-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_auto_20190414_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='status',
            field=models.CharField(choices=[('downloading', 'Downloading'), ('done', 'Done'), ('download_failed', 'Download failed')], default='downloading', editable=False, max_length=16),
        ),
    ]
