# Generated by Django 2.1.7 on 2019-04-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_publication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='local_file',
            field=models.FileField(editable=False, upload_to=''),
        ),
    ]
