# Generated by Django 2.1.7 on 2019-04-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_auto_20190414_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='version',
        ),
        migrations.AddField(
            model_name='annotation',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Annotated')], default=1, editable=False),
        ),
    ]
