# Generated by Django 2.1.7 on 2019-05-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0008_auto_20190423_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='status',
            new_name='download_status',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='page',
            name='status',
        ),
        migrations.AddField(
            model_name='annotation',
            name='annotation_status',
            field=models.CharField(choices=[('0:new', 'New'), ('1:auto_annotated', 'Auto-annotated'), ('2:annotated', 'Annotated'), ('3:super_annotated', 'Super-annotated')], default='0:new', editable=False, max_length=16),
        ),
        migrations.AddField(
            model_name='page',
            name='annotation_status',
            field=models.CharField(choices=[('0:new', 'New'), ('1:auto_annotated', 'Auto-annotated'), ('2:annotated', 'Annotated'), ('3:super_annotated', 'Super-annotated')], default='0:new', editable=False, max_length=16),
        ),
        migrations.AddField(
            model_name='publication',
            name='annotation_status',
            field=models.CharField(choices=[('0:new', 'New'), ('1:auto_annotated', 'Auto-annotated'), ('2:annotated', 'Annotated'), ('3:super_annotated', 'Super-annotated')], default='0:new', editable=False, max_length=16),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='created',
            field=models.DateTimeField(editable=False),
        ),
    ]
