# Generated by Django 2.1.7 on 2019-05-08 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0009_auto_20190508_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='annotation_status',
            field=models.CharField(choices=[('0:new', 'New'), ('1:auto_annotated', 'Auto-annotated'), ('2:annotated', 'Annotated'), ('3:super_annotated', 'Super-annotated')], default='0:new', editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='annotation_status',
            field=models.CharField(choices=[('0:new', 'New'), ('1:auto_annotated', 'Auto-annotated'), ('2:annotated', 'Annotated'), ('3:super_annotated', 'Super-annotated')], default='0:new', editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name='publication',
            name='annotation_status',
            field=models.CharField(choices=[('0:new', 'New'), ('1:auto_annotated', 'Auto-annotated'), ('2:annotated', 'Annotated'), ('3:super_annotated', 'Super-annotated')], default='0:new', editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name='publication',
            name='download_status',
            field=models.CharField(choices=[('downloading', 'Downloading'), ('done', 'Done'), ('download_failed', 'Download failed')], default='downloading', editable=False, max_length=32),
        ),
    ]
