# Generated by Django 2.1.7 on 2019-05-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0011_annotation_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
