# Generated by Django 2.1.8 on 2019-05-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0012_auto_20190509_1922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['number']},
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='annotation_used',
        ),
        migrations.AddField(
            model_name='annotation',
            name='annotations_used',
            field=models.ManyToManyField(null=True, related_name='_annotation_annotations_used_+', to='publications.Annotation'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='created',
            field=models.DateTimeField(editable=False),
        ),
    ]
