# Generated by Django 2.1.8 on 2019-05-23 21:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0014_annotation_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, null=True, size=None),
        ),
    ]
