# Generated by Django 2.1.14 on 2019-11-13 16:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0016_auto_20190525_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='ocr',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
