# Generated by Django 2.1.14 on 2019-12-01 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0017_page_ocr'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('key', models.CharField(max_length=512)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('key', models.CharField(max_length=512)),
                ('parent_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='publications.ObjectType')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='SubobjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('key', models.CharField(max_length=512)),
                ('valid_on', models.ManyToManyField(to='publications.ObjectType')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.AlterField(
            model_name='publication',
            name='download_status',
            field=models.CharField(choices=[('downloading', 'Downloading'), ('converting', 'Converting'), ('performing_ocr', 'Performing OCR'), ('done', 'Done'), ('download_failed', 'Download failed'), ('conversion_failed', 'Conversion failed')], default='downloading', editable=False, max_length=32),
        ),
    ]
