# Generated by Django 2.1.14 on 2019-12-01 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0018_auto_20191201_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationtag',
            name='sortkey',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='objecttype',
            name='sortkey',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subobjecttype',
            name='sortkey',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='objecttype',
            name='parent_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='publications.ObjectType'),
        ),
    ]
