# Generated by Django 2.1.14 on 2019-12-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0020_auto_20191201_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subobjecttype',
            name='valid_on',
        ),
        migrations.AddField(
            model_name='objecttype',
            name='subtypes',
            field=models.ManyToManyField(to='publications.SubobjectType'),
        ),
        migrations.AddField(
            model_name='subobjecttype',
            name='orientation',
            field=models.CharField(choices=[('neutral', 'Neutral'), ('vertical', 'Vertical'), ('horizontal', 'Horizontal')], default='neutral', max_length=32),
        ),
    ]
