# Generated by Django 2.1.7 on 2019-03-16 10:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('annotation_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='publications.Annotation')),
                ('annotation_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='publications.Annotation')),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('annotations', models.ManyToManyField(to='publications.Annotation')),
            ],
        ),
        migrations.AddField(
            model_name='score',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studies.Study'),
        ),
    ]
